<a href="https://colab.research.google.com/github/akashkumar123497/CSV-FILE/blob/main/SVM1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install preprocess1

Collecting preprocess1
  Downloading preprocess1-0.1.42-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from preprocess1) (1.6.1)
Collecting datetime (from preprocess1)
  Downloading datetime-6.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from preprocess1) (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from preprocess1) (2.1.3)
Requirement already satisfied: ipywidgets in /usr/local/lib/python3.13/dist-packages (from preprocess1) (7.7.1)
Requirement already satisfied: IPython in /usr/local/lib/python3.13/dist-packages (from preprocess1) (7.34.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from preprocess1) (1.16.3)
Collecting datefinder (from preprocess1)
  Downloading datefinder-1.0.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (11 kB)
Collecting pyod (from preprocess1)
  Downloading pyod-3.6.7-py3-none-any.whl.metadata (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 kB 4.4 MB/s eta 0:00:00
Requirement already satisfied: lightgbm in /usr/local/lib/python3.13/dist-packages (from preprocess1) (4.6.0)
Requirement already satisfied: regex>=2017.2.8 in /usr/local/lib/python3.13/dist-packages (from datefinder->preprocess1) (2025.11.3)
Requirement already satisfied: python-dateutil>=2.4.2 in /usr/local/lib/python3.13/dist-packages (from datefinder->preprocess1) (2.9.0.post0)
Requirement already satisfied: pytz in /usr/local/lib/python3.13/dist-packages (from datefinder->preprocess1) (2025.2)
Collecting zope.interface (from datetime->preprocess1)
  Downloading zope_interface-8.6-cp313-cp313-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 2.8 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (80.10.2)
Collecting jedi>=0.16 (from IPython->preprocess1)
  Downloading jedi-0.20.1-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: decorator in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (3.0.53)
Requirement already satisfied: pygments in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (2.21.0)
Requirement already satisfied: backcall in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (0.2.2)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.13/dist-packages (from IPython->preprocess1) (4.9.0)
Requirement already satisfied: ipykernel>=4.5.1 in /usr/local/lib/python3.13/dist-packages (from ipywidgets->preprocess1) (6.17.1)
Requirement already satisfied: ipython-genutils~=0.2.0 in /usr/local/lib/python3.13/dist-packages (from ipywidgets->preprocess1) (0.2.0)
Requirement already satisfied: widgetsnbextension~=3.6.0 in /usr/local/lib/python3.13/dist-packages (from ipywidgets->preprocess1) (3.6.10)
Requirement already satisfied: jupyterlab-widgets>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from ipywidgets->preprocess1) (3.0.17)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->preprocess1) (2026.4)
Requirement already satisfied: joblib>=1.5 in /usr/local/lib/python3.13/dist-packages (from pyod->preprocess1) (1.6.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.13/dist-packages (from pyod->preprocess1) (3.10.0)
Requirement already satisfied: numba>=0.51 in /usr/local/lib/python3.13/dist-packages (from pyod->preprocess1) (0.61.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->preprocess1) (3.7.0)
Requirement already satisfied: debugpy>=1.0 in /usr/local/lib/python3.13/dist-packages (from ipykernel>=4.5.1->ipywidgets->preprocess1) (1.8.15)
Requirement already satisfied: jupyter-client>=6.1.12 in /usr/local/lib/python3.13/dist-packages (from ipykernel>=4.5.1->ipywidgets->preprocess1) (7.4.9)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.13/dist-packages (from ipykernel>=4.5.1->ipywidgets->preprocess1) (1.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from ipykernel>=4.5.1->ipywidgets->preprocess1) (26.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.13/dist-packages (from ipykernel>=4.5.1->ipywidgets->preprocess1) (5.9.5)
Requirement already satisfied: pyzmq>=17 in /usr/local/lib/python3.13/dist-packages (from ipykernel>=4.5.1->ipywidgets->preprocess1) (26.2.1)
Requirement already satisfied: tornado>=6.1 in /usr/local/lib/python3.13/dist-packages (from ipykernel>=4.5.1->ipywidgets->preprocess1) (6.5.7)
Requirement already satisfied: parso<0.9.0,>=0.8.7 in /usr/local/lib/python3.13/dist-packages (from jedi>=0.16->IPython->preprocess1) (0.8.7)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=1.5->pyod->preprocess1) (3.1.2)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba>=0.51->pyod->preprocess1) (0.44.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.13/dist-packages (from pexpect>4.3->IPython->preprocess1) (0.7.0)
Requirement already satisfied: wcwidth>=0.1.4 in /usr/local/lib/python3.13/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->IPython->preprocess1) (0.9.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.4.2->datefinder->preprocess1) (1.17.0)
Requirement already satisfied: notebook>=4.4.1 in /usr/local/lib/python3.13/dist-packages (from widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (6.5.7)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pyod->preprocess1) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pyod->preprocess1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pyod->preprocess1) (4.66.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pyod->preprocess1) (1.5.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pyod->preprocess1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.13/dist-packages (from matplotlib->pyod->preprocess1) (3.3.3)
Requirement already satisfied: entrypoints in /usr/local/lib/python3.13/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->preprocess1) (0.4)
Requirement already satisfied: jupyter-core>=4.9.2 in /usr/local/lib/python3.13/dist-packages (from jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->preprocess1) (5.9.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (3.1.6)
Requirement already satisfied: argon2-cffi in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (25.1.0)
Requirement already satisfied: nbformat in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (5.11.1)
Requirement already satisfied: nbconvert>=5 in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (7.17.1)
Requirement already satisfied: Send2Trash>=1.8.0 in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.18.1)
Requirement already satisfied: prometheus-client in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.26.0)
Requirement already satisfied: nbclassic>=0.4.7 in /usr/local/lib/python3.13/dist-packages (from notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.3.3)
Requirement already satisfied: platformdirs>=2.5 in /usr/local/lib/python3.13/dist-packages (from jupyter-core>=4.9.2->jupyter-client>=6.1.12->ipykernel>=4.5.1->ipywidgets->preprocess1) (4.12.2)
Requirement already satisfied: notebook-shim>=0.2.3 in /usr/local/lib/python3.13/dist-packages (from nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.2.4)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (4.13.5)
Requirement already satisfied: bleach!=5.0.0 in /usr/local/lib/python3.13/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (6.4.0)
Requirement already satisfied: defusedxml in /usr/local/lib/python3.13/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in /usr/local/lib/python3.13/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.3.0)
Requirement already satisfied: markupsafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (3.0.3)
Requirement already satisfied: mistune<4,>=2.0.3 in /usr/local/lib/python3.13/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (3.3.4)
Requirement already satisfied: nbclient>=0.5.0 in /usr/local/lib/python3.13/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.10.4)
Requirement already satisfied: pandocfilters>=1.4.1 in /usr/local/lib/python3.13/dist-packages (from nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in /usr/local/lib/python3.13/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (2.22.2)
Requirement already satisfied: jsonschema>=2.6 in /usr/local/lib/python3.13/dist-packages (from nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (4.26.0)
Requirement already satisfied: argon2-cffi-bindings in /usr/local/lib/python3.13/dist-packages (from argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (26.1.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.13/dist-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.6.1)
Requirement already satisfied: tinycss2>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from bleach[css]!=5.0.0->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.5.1)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema>=2.6->nbformat->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (2026.6.3)
Requirement already satisfied: jupyter-server<3,>=1.8 in /usr/local/lib/python3.13/dist-packages (from notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (2.20.0)
Requirement already satisfied: cffi>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (2.1.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (2.10)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->nbconvert>=5->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (4.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.13/dist-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (3.0)
Requirement already satisfied: anyio>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (4.15.1)
Requirement already satisfied: jupyter-events>=0.11.0 in /usr/local/lib/python3.13/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in /usr/local/lib/python3.13/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.5.4)
Requirement already satisfied: websocket-client>=1.7 in /usr/local/lib/python3.13/dist-packages (from jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.9.2)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.13/dist-packages (from anyio>=3.1.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (3.20)
Requirement already satisfied: python-json-logger>=2.0.4 in /usr/local/lib/python3.13/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (4.2.0)
Requirement already satisfied: pyyaml>=5.3 in /usr/local/lib/python3.13/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (6.0.3)
Requirement already satisfied: rfc3339-validator in /usr/local/lib/python3.13/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (0.1.1)
Requirement already satisfied: fqdn in /usr/local/lib/python3.13/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.6.0)
Requirement already satisfied: isoduration in /usr/local/lib/python3.13/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in /usr/local/lib/python3.13/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.1.0)
Requirement already satisfied: uri-template in /usr/local/lib/python3.13/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in /usr/local/lib/python3.13/dist-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (25.10.0)
Requirement already satisfied: lark>=1.2.2 in /usr/local/lib/python3.13/dist-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.3.1)
Requirement already satisfied: arrow>=0.15.0 in /usr/local/lib/python3.13/dist-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=1.8->notebook-shim>=0.2.3->nbclassic>=0.4.7->notebook>=4.4.1->widgetsnbextension~=3.6.0->ipywidgets->preprocess1) (1.4.0)
Downloading preprocess1-0.1.42-py3-none-any.whl (41 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.2/41.2 kB 2.4 MB/s eta 0:00:00
Downloading datefinder-1.0.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 37.1 MB/s eta 0:00:00
Downloading datetime-6.0-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 3.7 MB/s eta 0:00:00
Downloading pyod-3.6.7-py3-none-any.whl (417 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 417.4/417.4 kB 22.2 MB/s eta 0:00:00
Downloading jedi-0.20.1-py2.py3-none-any.whl (4.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 54.1 MB/s eta 0:00:00
Downloading zope_interface-8.6-cp313-cp313-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (270 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 270.6/270.6 kB 16.0 MB/s eta 0:00:00
Installing collected packages: zope.interface, jedi, datetime, datefinder, pyod, preprocess1
Successfully installed datefinder-1.0.0 datetime-6.0 jedi-0.20.1 preprocess1-0.1.42 pyod-3.6.7 zope.interface-8.6

In [10]:
import numpy as np
import pickle
import pandas as pd
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import SMOTE
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [11]:
df=pd.read_csv("/content/loan_approved (1).csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [12]:
df.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area',
       'Loan_Status (Approved)'],
      dtype='object')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Loan_ID                 614 non-null    object
 1   Gender                  601 non-null    object
 2   Married                 611 non-null    object
 3   Dependents              599 non-null    object
 4   Education               614 non-null    object
 5   Self_Employed           582 non-null    object
 6   ApplicantIncome         614 non-null    int64
 7   CoapplicantIncome       614 non-null    float64
 8   LoanAmount              592 non-null    float64
 9   Loan_Amount_Term        600 non-null    float64
 10  Credit_History          564 non-null    float64
 11  Property_Area           614 non-null    object
 12  Loan_Status (Approved)  614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [14]:
df.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [15]:
df.isnull().sum()

Loan_ID                    0
Gender                    13
Married                    3
Dependents                15
Education                  0
Self_Employed             32
ApplicantIncome            0
CoapplicantIncome          0
LoanAmount                22
Loan_Amount_Term          14
Credit_History            50
Property_Area              0
Loan_Status (Approved)     0
dtype: int64

In [17]:
df.tail()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status (Approved)
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [18]:
df.shape

(614, 13)

In [20]:
df.loc[df['Gender'].isnull(),'Gender']='Male'

In [21]:
df.loc[df['Married'].isnull(),'Married']='Yes'

In [22]:
df.loc[df['Dependents'].isnull(),'Dependents']='0'

In [23]:
df.loc[df['Self_Employed'].isnull(),'Self_Employed']='No'

In [24]:
df.loc[df['LoanAmount'].isnull(),'LoanAmount']=df['LoanAmount'].median()

In [25]:
df.loc[df['Loan_Amount_Term'].isnull(),'Loan_Amount_Term']=360.0

In [26]:
df.loc[df['Credit_History'].isnull(),'Credit_History']=0.0

In [27]:
df.isnull().sum()

Loan_ID                   0
Gender                    0
Married                   0
Dependents                0
Education                 0
Self_Employed             0
ApplicantIncome           0
CoapplicantIncome         0
LoanAmount                0
Loan_Amount_Term          0
Credit_History            0
Property_Area             0
Loan_Status (Approved)    0
dtype: int64